window.NutriData = {
  communities: {
    "New York City": { lat: 40.7128, lng: -74.006, country: "United States" },
    "Los Angeles": { lat: 34.0522, lng: -118.2437, country: "United States" },
    "Chicago": { lat: 41.8781, lng: -87.6298, country: "United States" },
    "Houston": { lat: 29.7604, lng: -95.3698, country: "United States" },
    "Phoenix": { lat: 33.4484, lng: -112.074, country: "United States" },
    "Philadelphia": { lat: 39.9526, lng: -75.1652, country: "United States" },
    "San Antonio": { lat: 29.4241, lng: -98.4936, country: "United States" },
    "San Diego": { lat: 32.7157, lng: -117.1611, country: "United States" },
    "Dallas": { lat: 32.7767, lng: -96.797, country: "United States" },
    "San Jose": { lat: 37.3382, lng: -121.8863, country: "United States" },
    "Austin": { lat: 30.2672, lng: -97.7431, country: "United States" },
    "Jacksonville": { lat: 30.3322, lng: -81.6557, country: "United States" },
    "Fort Worth": { lat: 32.7555, lng: -97.3308, country: "United States" },
    "Columbus": { lat: 39.9612, lng: -82.9988, country: "United States" },
    "Charlotte": { lat: 35.2271, lng: -80.8431, country: "United States" },
    "San Francisco": { lat: 37.7749, lng: -122.4194, country: "United States" },
    "Indianapolis": { lat: 39.7684, lng: -86.1581, country: "United States" },
    "Seattle": { lat: 47.6062, lng: -122.3321, country: "United States" },
    "Denver": { lat: 39.7392, lng: -104.9903, country: "United States" },
    "Washington DC": { lat: 38.9072, lng: -77.0369, country: "United States" },
    "Boston": { lat: 42.3601, lng: -71.0589, country: "United States" },
    "Nashville": { lat: 36.1627, lng: -86.7816, country: "United States" },
    "Detroit": { lat: 42.3314, lng: -83.0458, country: "United States" },
    "Baltimore": { lat: 39.2904, lng: -76.6122, country: "United States" },
    "Milwaukee": { lat: 43.0389, lng: -87.9065, country: "United States" },
    "Portland": { lat: 45.5152, lng: -122.6784, country: "United States" },
    "Las Vegas": { lat: 36.1699, lng: -115.1398, country: "United States" },
    "Oklahoma City": { lat: 35.4676, lng: -97.5164, country: "United States" },
    "Louisville": { lat: 38.2527, lng: -85.7585, country: "United States" },
    "Memphis": { lat: 35.1495, lng: -90.049, country: "United States" },
    "New Orleans": { lat: 29.9511, lng: -90.0715, country: "United States" },
    "Miami": { lat: 25.7617, lng: -80.1918, country: "United States" },
    "Tampa": { lat: 27.9506, lng: -82.4572, country: "United States" },
    "Minneapolis": { lat: 44.9778, lng: -93.265, country: "United States" },
    "Kansas City": { lat: 39.0997, lng: -94.5786, country: "United States" },
    "St. Louis": { lat: 38.627, lng: -90.1994, country: "United States" },
    "Cleveland": { lat: 41.4993, lng: -81.6944, country: "United States" },
    "Pittsburgh": { lat: 40.4406, lng: -79.9959, country: "United States" },
    "Cincinnati": { lat: 39.1031, lng: -84.512, country: "United States" },
    "Raleigh": { lat: 35.7796, lng: -78.6382, country: "United States" },
    "Sacramento": { lat: 38.5816, lng: -121.4944, country: "United States" },
    "Salt Lake City": { lat: 40.7608, lng: -111.891, country: "United States" },
    "Albuquerque": { lat: 35.0844, lng: -106.6504, country: "United States" },
    "El Paso": { lat: 31.7619, lng: -106.485, country: "United States" },
    "Fresno": { lat: 36.7378, lng: -119.7871, country: "United States" },
    "Buffalo": { lat: 42.8864, lng: -78.8784, country: "United States" },
    "Richmond": { lat: 37.5407, lng: -77.436, country: "United States" },
    "Providence": { lat: 41.824, lng: -71.4128, country: "United States" }
  },

  languages: [
    "English", "Spanish", "French", "Arabic", "Hindi", "Bengali", "Portuguese", "Russian", "Urdu",
    "Indonesian", "German", "Japanese", "Swahili", "Marathi", "Telugu", "Turkish", "Tamil", "Vietnamese",
    "Korean", "Persian", "Italian", "Thai", "Gujarati", "Polish", "Ukrainian", "Punjabi", "Malayalam",
    "Kannada", "Odia", "Romanian", "Dutch", "Greek", "Czech", "Hungarian", "Azerbaijani", "Burmese",
    "Nepali", "Sinhala", "Khmer", "Lao", "Filipino", "Malay", "Amharic", "Hausa", "Yoruba", "Igbo",
    "Somali", "Tigrinya", "Zulu", "Xhosa", "Shona", "Kinyarwanda", "Kirundi", "Wolof", "Fula", "Lingala",
    "Hebrew", "Pashto", "Dari", "Kazakh", "Uzbek", "Mongolian", "Serbian", "Croatian", "Bulgarian",
    "Slovak", "Slovenian", "Finnish", "Swedish", "Norwegian", "Danish", "Catalan", "Basque", "Galician",
    "Quechua", "Aymara", "Guarani", "Creole Haitian", "Mandarin Chinese", "Cantonese", "Bhojpuri", "Maithili"
  ],

  foods: [
    { id: "beans", name: "Beans", nutrients: ["protein", "iron", "folate"], cost: 1.2, score: 82 },
    { id: "lentils", name: "Lentils", nutrients: ["protein", "iron"], cost: 1.1, score: 85 },
    { id: "chickpeas", name: "Chickpeas", nutrients: ["protein", "iron", "fiber"], cost: 1.2, score: 83 },
    { id: "peas", name: "Green peas", nutrients: ["protein", "fiber", "folate"], cost: 1.1, score: 77 },
    { id: "soybeans", name: "Soybeans", nutrients: ["protein", "iron", "fat"], cost: 1.4, score: 86 },
    { id: "tofu", name: "Tofu", nutrients: ["protein", "calcium"], cost: 1.5, score: 78 },
    { id: "eggs", name: "Eggs", nutrients: ["protein", "vitaminB12", "fat"], cost: 1.8, score: 79 },
    { id: "milk", name: "Milk", nutrients: ["protein", "calcium", "fat"], cost: 1.5, score: 72 },
    { id: "yogurt", name: "Yogurt", nutrients: ["protein", "calcium"], cost: 1.4, score: 70 },
    { id: "sardines", name: "Sardines", nutrients: ["protein", "omega3", "calcium"], cost: 2.2, score: 88 },
    { id: "chicken", name: "Chicken", nutrients: ["protein", "fat"], cost: 2.4, score: 74 },
    { id: "beef", name: "Beef", nutrients: ["protein", "iron", "zinc"], cost: 2.9, score: 73 },
    { id: "millet", name: "Millet", nutrients: ["fiber", "iron", "carbs"], cost: 0.8, score: 76 },
    { id: "maize", name: "Maize", nutrients: ["carbs", "fiber"], cost: 0.6, score: 60 },
    { id: "rice", name: "Rice", nutrients: ["carbs"], cost: 0.9, score: 58 },
    { id: "brown_rice", name: "Brown rice", nutrients: ["carbs", "fiber"], cost: 1.1, score: 69 },
    { id: "wheat", name: "Wheat", nutrients: ["carbs", "fiber"], cost: 0.9, score: 62 },
    { id: "oats", name: "Oats", nutrients: ["carbs", "fiber", "iron"], cost: 1.2, score: 75 },
    { id: "sweet_potato", name: "Sweet potato", nutrients: ["vitaminA", "carbs", "fiber"], cost: 0.7, score: 78 },
    { id: "potato", name: "Potato", nutrients: ["carbs", "potassium"], cost: 0.7, score: 61 },
    { id: "plantain", name: "Plantain", nutrients: ["carbs", "potassium"], cost: 0.8, score: 64 },
    { id: "groundnuts", name: "Groundnuts", nutrients: ["protein", "fat", "zinc"], cost: 1.0, score: 74 },
    { id: "sesame", name: "Sesame seeds", nutrients: ["fat", "calcium", "iron"], cost: 1.5, score: 76 },
    { id: "spinach", name: "Spinach", nutrients: ["iron", "folate", "vitaminA"], cost: 0.9, score: 81 },
    { id: "kale", name: "Kale", nutrients: ["iron", "vitaminA", "fiber"], cost: 0.8, score: 80 },
    { id: "cabbage", name: "Cabbage", nutrients: ["fiber", "vitaminC"], cost: 0.6, score: 62 },
    { id: "broccoli", name: "Broccoli", nutrients: ["vitaminC", "fiber", "folate"], cost: 1.3, score: 75 },
    { id: "carrot", name: "Carrot", nutrients: ["vitaminA", "fiber"], cost: 0.7, score: 72 },
    { id: "tomato", name: "Tomato", nutrients: ["vitaminC", "fiber"], cost: 0.7, score: 66 },
    { id: "onion", name: "Onion", nutrients: ["fiber"], cost: 0.5, score: 55 },
    { id: "banana", name: "Banana", nutrients: ["potassium", "carbs"], cost: 0.6, score: 65 },
    { id: "orange", name: "Orange", nutrients: ["vitaminC", "fiber"], cost: 0.8, score: 68 },
    { id: "apple", name: "Apple", nutrients: ["fiber", "vitaminC"], cost: 1.0, score: 64 },
    { id: "avocado", name: "Avocado", nutrients: ["fat", "fiber", "potassium"], cost: 1.2, score: 72 },
    { id: "fortified_flour", name: "Fortified flour", nutrients: ["iron", "folate", "carbs"], cost: 1.2, score: 77 },
    { id: "fortified_cereal", name: "Fortified cereal", nutrients: ["iron", "folate", "carbs"], cost: 1.6, score: 79 },
    { id: "peanut_paste", name: "Peanut paste", nutrients: ["protein", "fat", "calories"], cost: 1.2, score: 84 },
    { id: "black_beans", name: "Black beans", nutrients: ["protein", "iron", "fiber"], cost: 1.2, score: 82 },
    { id: "kidney_beans", name: "Kidney beans", nutrients: ["protein", "iron", "fiber"], cost: 1.1, score: 81 },
    { id: "red_lentils", name: "Red lentils", nutrients: ["protein", "iron"], cost: 1.0, score: 86 },
    { id: "whole_wheat_bread", name: "Whole wheat bread", nutrients: ["carbs", "fiber", "iron"], cost: 1.0, score: 67 }
  ],

  resources: [
    { id: "res-ny-01", name: "Food Bank For New York City", type: "Food Support", lat: 40.8069, lng: -73.9384, services: ["Pantry locator", "SNAP outreach", "Mobile pantry"], open: "Hours vary; call ahead" },
    { id: "res-ny-02", name: "City Harvest", type: "Food Support", lat: 40.7512, lng: -73.9936, services: ["Rescue food distribution", "Mobile markets"], open: "Mon-Fri 09:00-17:00" },
    { id: "res-ny-03", name: "Community Healthcare Network", type: "Clinic", lat: 40.7178, lng: -73.9892, services: ["Primary care", "Nutrition counseling", "WIC referrals"], open: "Mon-Sat; by site" },
    { id: "res-ny-04", name: "Catholic Charities of New York", type: "NGO", lat: 40.7648, lng: -73.9808, services: ["Emergency food", "Case management"], open: "Hours vary; call ahead" },

    { id: "res-la-01", name: "Los Angeles Regional Food Bank", type: "Food Support", lat: 34.0368, lng: -118.2232, services: ["Food pantry network", "CalFresh support"], open: "Mon-Fri 08:00-17:00" },
    { id: "res-la-02", name: "Project Angel Food", type: "NGO", lat: 34.0906, lng: -118.3613, services: ["Home-delivered meals", "Nutrition support"], open: "Mon-Fri 08:00-17:00" },
    { id: "res-la-03", name: "AltaMed Health Services", type: "Clinic", lat: 34.0134, lng: -118.2104, services: ["Primary care", "Pediatric care", "Dietitian support"], open: "Mon-Sat; by site" },

    { id: "res-chi-01", name: "Greater Chicago Food Depository", type: "Food Support", lat: 41.8178, lng: -87.6655, services: ["Pantry partners", "Produce programs"], open: "Mon-Fri 08:30-16:30" },
    { id: "res-chi-02", name: "Cook County Health", type: "Clinic", lat: 41.8722, lng: -87.6643, services: ["Primary care", "Nutrition care", "Social services"], open: "Mon-Fri; by clinic" },
    { id: "res-chi-03", name: "Catholic Charities of Chicago", type: "NGO", lat: 41.8898, lng: -87.6312, services: ["Emergency assistance", "Food referrals"], open: "Hours vary; call ahead" },

    { id: "res-hou-01", name: "Houston Food Bank", type: "Food Support", lat: 29.7805, lng: -95.2926, services: ["Food distribution", "SNAP outreach"], open: "Mon-Fri 08:00-17:00" },
    { id: "res-hou-02", name: "Legacy Community Health", type: "Clinic", lat: 29.7392, lng: -95.3812, services: ["Primary care", "Family nutrition support"], open: "Mon-Sat; by site" },
    { id: "res-hou-03", name: "BakerRipley", type: "NGO", lat: 29.7496, lng: -95.3295, services: ["Food support", "Family services"], open: "Mon-Fri 08:30-17:00" },

    { id: "res-phx-01", name: "St. Mary's Food Bank", type: "Food Support", lat: 33.4546, lng: -112.1112, services: ["Pantry network", "Emergency food boxes"], open: "Mon-Fri 07:00-15:00" },
    { id: "res-phx-02", name: "Valleywise Community Health Center", type: "Clinic", lat: 33.4537, lng: -112.0734, services: ["Primary care", "Nutrition counseling"], open: "Mon-Fri; by clinic" },
    { id: "res-phx-03", name: "Arizona Food Bank Network", type: "NGO", lat: 33.4298, lng: -111.9985, services: ["Food bank network routing", "Policy and referral support"], open: "Mon-Fri 09:00-17:00" },

    { id: "res-phl-01", name: "Philabundance", type: "Food Support", lat: 39.9332, lng: -75.1375, services: ["Food distribution", "Community kitchens"], open: "Mon-Fri 08:00-16:00" },
    { id: "res-phl-02", name: "Philadelphia FIGHT", type: "Clinic", lat: 39.9509, lng: -75.1564, services: ["Primary care", "Nutrition care"], open: "Mon-Fri; by clinic" },
    { id: "res-phl-03", name: "Project HOME", type: "NGO", lat: 39.9645, lng: -75.1594, services: ["Housing + food support", "Care coordination"], open: "Hours vary; call ahead" },

    { id: "res-sa-01", name: "San Antonio Food Bank", type: "Food Support", lat: 29.4964, lng: -98.5897, services: ["Pantry network", "Children and seniors programs"], open: "Mon-Fri 08:00-17:00" },
    { id: "res-sa-02", name: "CentroMed", type: "Clinic", lat: 29.4255, lng: -98.4946, services: ["Primary care", "Pediatric care", "Nutrition support"], open: "Mon-Sat; by site" },
    { id: "res-sa-03", name: "Catholic Charities, Archdiocese of San Antonio", type: "NGO", lat: 29.4234, lng: -98.4932, services: ["Emergency assistance", "Food referrals"], open: "Mon-Fri 08:30-17:00" },

    { id: "res-sd-01", name: "San Diego Food Bank", type: "Food Support", lat: 32.7096, lng: -117.1512, services: ["Food distributions", "CalFresh outreach"], open: "Mon-Fri 08:00-17:00" },
    { id: "res-sd-02", name: "Family Health Centers of San Diego", type: "Clinic", lat: 32.7069, lng: -117.1617, services: ["Primary care", "Nutrition counseling"], open: "Mon-Sat; by site" },
    { id: "res-sd-03", name: "Jewish Family Service of San Diego", type: "NGO", lat: 32.8751, lng: -117.2172, services: ["Food pantry", "Case management"], open: "Mon-Fri; by service" },

    { id: "res-dal-01", name: "North Texas Food Bank", type: "Food Support", lat: 32.9015, lng: -96.8847, services: ["Pantry network", "School pantry support"], open: "Mon-Fri 08:00-17:00" },
    { id: "res-dal-02", name: "Parkland Health Community Clinics", type: "Clinic", lat: 32.8091, lng: -96.8378, services: ["Primary care", "Dietitian services"], open: "Mon-Fri; by clinic" },
    { id: "res-dal-03", name: "Catholic Charities Dallas", type: "NGO", lat: 32.7832, lng: -96.8003, services: ["Food programs", "Family support"], open: "Mon-Fri 08:30-17:00" },

    { id: "res-aus-01", name: "Central Texas Food Bank", type: "Food Support", lat: 30.211, lng: -97.6895, services: ["Pantry support", "Mobile distributions"], open: "Mon-Fri 08:00-17:00" },
    { id: "res-aus-02", name: "CommUnityCare Health Centers", type: "Clinic", lat: 30.2678, lng: -97.7393, services: ["Primary care", "Nutrition support"], open: "Mon-Sat; by site" },
    { id: "res-aus-03", name: "Caritas of Austin", type: "NGO", lat: 30.2638, lng: -97.7405, services: ["Food pantry", "Housing + case support"], open: "Mon-Fri 08:30-16:30" },

    { id: "res-sf-01", name: "SF-Marin Food Bank", type: "Food Support", lat: 37.7428, lng: -122.4077, services: ["Pantry distributions", "Home-delivered groceries"], open: "Mon-Fri 08:00-17:00" },
    { id: "res-sf-02", name: "San Francisco Community Clinic Consortium", type: "Clinic", lat: 37.7759, lng: -122.4193, services: ["Clinic network", "Primary care referrals"], open: "Mon-Fri 09:00-17:00" },
    { id: "res-sf-03", name: "Glide", type: "NGO", lat: 37.7812, lng: -122.4103, services: ["Meal program", "Family support services"], open: "Daily; check service hours" },

    { id: "res-sea-01", name: "Food Lifeline", type: "Food Support", lat: 47.579, lng: -122.3334, services: ["Pantry partners", "Regional food distribution"], open: "Mon-Fri 08:00-17:00" },
    { id: "res-sea-02", name: "Seattle Indian Health Board", type: "Clinic", lat: 47.5998, lng: -122.3278, services: ["Primary care", "Nutrition and wellness"], open: "Mon-Fri; by clinic" },
    { id: "res-sea-03", name: "Solid Ground", type: "NGO", lat: 47.679, lng: -122.3264, services: ["Food access", "Benefits support"], open: "Mon-Fri 09:00-17:00" },

    { id: "res-den-01", name: "Food Bank of the Rockies", type: "Food Support", lat: 39.7746, lng: -104.9377, services: ["Pantry network", "Food boxes"], open: "Mon-Fri 08:00-17:00" },
    { id: "res-den-02", name: "Denver Health Community Health Services", type: "Clinic", lat: 39.7294, lng: -104.9915, services: ["Primary care", "Nutrition counseling"], open: "Mon-Fri; by clinic" },
    { id: "res-den-03", name: "Metro Caring", type: "NGO", lat: 39.7441, lng: -104.9892, services: ["Fresh food market", "Nutrition education"], open: "Tue-Sat; by program" },

    { id: "res-dc-01", name: "Capital Area Food Bank", type: "Food Support", lat: 38.9178, lng: -76.9945, services: ["Pantry distribution", "SNAP support"], open: "Mon-Fri 08:00-17:00" },
    { id: "res-dc-02", name: "Unity Health Care", type: "Clinic", lat: 38.9063, lng: -77.0169, services: ["Primary care", "Nutrition and diabetes support"], open: "Mon-Sat; by site" },
    { id: "res-dc-03", name: "Bread for the City", type: "NGO", lat: 38.9153, lng: -77.0241, services: ["Food pantry", "Social services"], open: "Mon-Fri; by service" },

    { id: "res-bos-01", name: "Greater Boston Food Bank", type: "Food Support", lat: 42.3447, lng: -71.0415, services: ["Food distribution", "Pantry support"], open: "Mon-Fri 08:00-17:00" },
    { id: "res-bos-02", name: "Boston Medical Center", type: "Clinic", lat: 42.3347, lng: -71.0741, services: ["Primary care", "Clinical nutrition"], open: "Mon-Fri; by clinic" },
    { id: "res-bos-03", name: "Project Bread", type: "NGO", lat: 42.3524, lng: -71.0556, services: ["FoodSource Hotline", "School meal support"], open: "Mon-Fri 08:00-17:00" },

    { id: "res-mia-01", name: "Feeding South Florida", type: "Food Support", lat: 25.9387, lng: -80.2729, services: ["Pantry network", "Mobile distributions"], open: "Mon-Fri 08:00-17:00" },
    { id: "res-mia-02", name: "Miami-Dade Community Health Center", type: "Clinic", lat: 25.7736, lng: -80.2092, services: ["Primary care", "Nutrition support"], open: "Mon-Sat; by site" },
    { id: "res-mia-03", name: "Camillus House", type: "NGO", lat: 25.7809, lng: -80.2124, services: ["Meals", "Case management"], open: "Daily; by service" },

    { id: "res-min-01", name: "Second Harvest Heartland", type: "Food Support", lat: 44.9895, lng: -93.2667, services: ["Food bank network", "Pantry support"], open: "Mon-Fri 08:00-17:00" },
    { id: "res-min-02", name: "Hennepin Healthcare", type: "Clinic", lat: 44.9727, lng: -93.2622, services: ["Primary care", "Nutrition and chronic care"], open: "Mon-Fri; by clinic" },
    { id: "res-min-03", name: "Catholic Charities Twin Cities", type: "NGO", lat: 44.9499, lng: -93.0971, services: ["Food shelf", "Emergency assistance"], open: "Mon-Fri 08:30-17:00" },

    { id: "res-por-01", name: "Oregon Food Bank", type: "Food Support", lat: 45.5483, lng: -122.6376, services: ["Pantry network", "Food access referrals"], open: "Mon-Fri 08:00-17:00" },
    { id: "res-por-02", name: "Multnomah County Community Health Center", type: "Clinic", lat: 45.5237, lng: -122.6769, services: ["Primary care", "Nutrition support"], open: "Mon-Fri; by clinic" },
    { id: "res-por-03", name: "Transition Projects", type: "NGO", lat: 45.5231, lng: -122.6759, services: ["Meal support", "Housing and case support"], open: "Daily; by service" },

    { id: "res-slc-01", name: "Utah Food Bank", type: "Food Support", lat: 40.7218, lng: -111.9132, services: ["Pantry support", "Rural distributions"], open: "Mon-Fri 08:00-17:00" },
    { id: "res-slc-02", name: "Maliheh Free Clinic", type: "Clinic", lat: 40.7631, lng: -111.8882, services: ["Primary care", "Nutrition counseling"], open: "Mon-Fri; by clinic" },
    { id: "res-slc-03", name: "Catholic Community Services of Utah", type: "NGO", lat: 40.7479, lng: -111.9006, services: ["Food pantry", "Refugee and family support"], open: "Mon-Fri 08:30-17:00" }
  ]
};
